### ISSUE TITLE
WTF!

### ISSUE THREAD

**Issue by Cryptobertl** [thisrepo/dog#46]
No one really understands this?

**Comment by Eriwa00** [comment]
Solana folks impatient 😂

**Comment by Tarryco** [comment]
Continue building

**Comment by PuppyThick16** [comment]
Continue building. It will surely send.

**Comment by Cryptobertl** [comment]
It will

**Comment by PuppyThick16** [comment]
CTO?

**Comment by HeroLogis** [comment]
I`m still hold, any hope for this project?

**Comment by D1zzy013** [comment]
this new Meta will FLYYYYYYYYYYYYYYYYYYYYY

**Comment by PuppyThick16** [comment]
I am also still hodling. Actually, I made a re-entry at 19k mcap.

**Comment by Cryptobertl** [comment]
Me too I also rebought at 30k and from here we nicely go

**Comment by PuppyThick16** [comment]
Wew! I didn’t know that it pumped again when I was too busy. Lol!

**Comment by Cryptobertl** [comment]
Mate that’s a long term here you will make a 100-1000x easily

**Comment by PuppyThick16** [comment]
Yeah! I believe too, mate.
But we need an update from repo.
Codes, cto, etc.

**Comment by BillyTsuki** [comment]
stay believing, have some conviction

**Comment by Cryptobertl** [comment]
By the way it’s an official cto?

**Comment by httpscure** [comment]
> By the way it’s an official cto?

not even cto i think. the project owner still here and updating stuff

**Comment by Cryptobertl** [comment]
https://t.me/ghdogsol

**Comment by Cryptobertl** [comment]
Ok good so the tg link will not be cto

**Comment by Cryptobertl** [comment]
I would say more people realise now about this wtf is already done
